// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1rV5wnPirvZHQjyDowggdngru5jIUUyk',
    appId: '1:255497040130:android:76c0575be85fa8de74921b',
    messagingSenderId: '255497040130',
    projectId: 'bidding-ee056',
    databaseURL: 'https://bidding-ee056-default-rtdb.firebaseio.com',
    storageBucket: 'bidding-ee056.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAJqDejx9PKrutYygBJ5cmvSFXAeF94Zk',
    appId: '1:255497040130:ios:32d85ea3a9bfe83274921b',
    messagingSenderId: '255497040130',
    projectId: 'bidding-ee056',
    databaseURL: 'https://bidding-ee056-default-rtdb.firebaseio.com',
    storageBucket: 'bidding-ee056.firebasestorage.app',
    iosClientId:
        '255497040130-tjuttb6p8mre59hv0fpd9s95g4mb3ord.apps.googleusercontent.com',
    iosBundleId: 'com.dirham365.dirham',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxbBnfcik23XD0EuB8LCjcJpbtPhURUoM',
    appId: '1:255497040130:web:997f70d3769f87a174921b',
    messagingSenderId: '255497040130',
    projectId: 'bidding-ee056',
    authDomain: 'bidding-ee056.firebaseapp.com',
    databaseURL: 'https://bidding-ee056-default-rtdb.firebaseio.com',
    storageBucket: 'bidding-ee056.firebasestorage.app',
    measurementId: 'G-40HGZV2J5E',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAJqDejx9PKrutYygBJ5cmvSFXAeF94Zk',
    appId: '1:255497040130:ios:32d85ea3a9bfe83274921b',
    messagingSenderId: '255497040130',
    projectId: 'bidding-ee056',
    databaseURL: 'https://bidding-ee056-default-rtdb.firebaseio.com',
    storageBucket: 'bidding-ee056.firebasestorage.app',
    iosClientId:
        '255497040130-tjuttb6p8mre59hv0fpd9s95g4mb3ord.apps.googleusercontent.com',
    iosBundleId: 'com.dirham365.dirham',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1haZ9mt_GGYvZ4G84rROjGQ41NpNLMM0',
    appId: '1:255497040130:web:0f1de0c7bb0f9ea874921b',
    messagingSenderId: '255497040130',
    projectId: 'bidding-ee056',
    authDomain: 'bidding-ee056.firebaseapp.com',
    databaseURL: 'https://bidding-ee056-default-rtdb.firebaseio.com',
    storageBucket: 'bidding-ee056.firebasestorage.app',
    measurementId: 'G-M4CZYBCD4K',
  );
}
